export const LIKE_MOVIE_SUCCESS = 'LIKE_MOVIE_SUCCESS';
export const UNLIKE_MOVIE_SUCCESS = 'UNLIKE_MOVIE_SUCCESS';

export const LOAD_MOVIE_SUCCESS = 'LOAD_MOVIE_SUCCESS';
export const LOAD_MOVIE_FAILURE = 'LOAD_MOVIE_FAILURE';